server:
  port: 9090
spring:
  cloud:
    gateway:
      routes:
        - id: user_service
          uri: 'http://146.59.234.45:8081'
          predicates:
            - Path=/users/**
        - id: case_service
          uri: 'http://146.59.234.45:8090'
          predicates:
            - Path=/positive/**
        - id: kafka_service
          uri: 'http://146.59.234.45:9000'
          predicates:
            - Path=/stream/location/**
        - id: notification_service
            uri: 'http://146.59.234.45:8089'
            predicates:
              - Path=/notification/**
        - id: location_service
            uri: 'http://146.59.234.45:8091'
            predicates:
              - Path=/locations/**