server:
  port: 8082
spring:
  cloud:
    gateway:
      routes:
        - id: user_service
          uri: 'https://alert-covid.ovh:8081'
          predicates:
            - Path=/users/**
        - id: case_service
          uri: 'https://alert-covid.ovh:8090'
          predicates:
            - Path=/positive/**
        - id: kafka_service
          uri: 'https://alert-covid.ovh:9000'
          predicates:
            - Path=/stream/location/**
        - id: notification_service
          uri: 'https://alert-covid.ovh:8089'
          predicates:
            - Path=/notification/**
        - id: location_service
          uri: 'https://alert-covid.ovh:8091'
          predicates:
            - Path=/locations/**