server:
  port: 9090
spring:
  cloud:
    gateway:
      routes:
        - id: user_service
          uri: 'http://localhost:8080'
          predicates:
            - Path=/users/**
        - id: case_service
          uri: 'http://localhost:8090'
          predicates:
            - Path=/positive/**
        - id: kafka_service
          uri: 'http://localhost:9000'
          predicates:
            - Path=/stream/location/**