server:
  port: 9090
spring:
  cloud:
    gateway:
      routes:
        - id: user_service
          uri: 'http://localhost:8080'
          predicates:
            - Path=/users/**
        - id: notification_service
          uri: 'http://localhost:8089'
          predicates:
            - Path=/notification/**
